### ISSUE TITLE
Nice work, but missing support for TCP and TLS

### ISSUE THREAD

**Issue by ststeiger** [jchristn/WatsonSyslogServer#1]
Nice work ! 
Didn't realize syslog was as simple as that. 
Your server was missing support for TCP and TLS. 
I've added it !

See https://github.com/ststeiger/NetCoreSyslogServer

**Comment by jchristn** [comment]
That's rad @ststeiger - nice job!  I'll amend the README and point to your repo for anyone that is interested in syslog beyond UDP, and including TCP/TLS.  Cheers, Joel

**Comment by jchristn** [comment]
Just updated my README with a link to your repo.  Cheers!
